"""
LLM-assisted features for issueWriter, driven through the Claude Code CLI.

Two features live here:

  1. Reproduction steps: when an issue body has no numbered steps/bullets the
     regex parser can pick up, ask Claude to either EXTRACT steps written in
     prose or INFER plausible steps from the title/body/comments/linked PRs.

  2. "Other" triage: for issues that matched no sheet and no deterministic
     category, ask Claude whether they should have been in the spreadsheet,
     are missing a label, or are correctly excluded. Claude may run read-only
     `gh` commands to inspect linked pull requests.

All results are cached in ai_cache.json keyed by repo#number and the issue's
updated_at, so re-running the script does not re-pay for unchanged issues.
"""

import re

from claude_cli import ClaudeCliError, empty_usage, run_claude

MAX_BODY_CHARS = 8000
MAX_COMMENTS = 8
MAX_COMMENT_CHARS = 1500
MAX_LINKED_PRS = 5

# Read-only gh commands Claude may run during triage without a prompt.
TRIAGE_ALLOWED_TOOLS = [
    "Bash(gh issue view *)",
    "Bash(gh pr view *)",
    "Bash(gh pr diff *)",
    "Bash(gh pr list *)",
]
TRIAGE_MAX_TURNS = 8
TRIAGE_TIMEOUT = 600
REPRO_TIMEOUT = 240

# Markers written into the sheet so testers can tell AI rows from regex rows.
MARKER_DETECTED_VERIFIED = "These steps were autogenerated (AI-verified as real test steps)"
MARKER_EXTRACTED = "These steps were AI-extracted from the issue text - verify!"
MARKER_INFERRED = "These steps were AI-INFERRED (issue had no steps) - verify before testing!"
MARKER_NOT_TESTABLE = "AI assessment: NOT MANUALLY TESTABLE - confirm, then mark N/A"
MARKER_NO_STEPS = "AI found no usable steps - write them manually"


# ── Prompts and schemas ──────────────────────────────────────────────────────

REPRO_SYSTEM_PROMPT = """\
You write manual QA test steps for the Vantiq IDE, a browser-based low-code \
development environment. Each step is one tester action and may have an \
expected result.

You will receive one GitHub issue (title, labels, body, comments, linked PRs). \
Decide which case applies:

- "detected_valid": only when the input includes a section "LINES THE PARSER \
DETECTED AS STEPS". Those are numbered or bulleted lines a simple regex pulled \
from the body. Use this mode when they are genuine reproduction or test steps: \
actions a tester performs, in order. Return an empty steps list; the original \
lines will be used unchanged. Do NOT use this mode when the lines are something \
else, such as a feature checklist, requirements, release notes, a list of \
affected files or resources, or acceptance criteria written as outcomes rather \
than actions. In that case ignore those lines and pick one of the modes below.
- "extracted": the issue text already describes how to reproduce or exercise \
the change, in any form (prose, "Repro:", "Steps:", a sentence like "when I \
click X then Y happens"). Turn that into steps faithfully. Do not add steps \
the text does not support.
- "inferred": the text has no usable steps but has enough detail (title, \
description, PR info) to write plausible steps a tester could try to verify \
the fix or feature. Use generic wording where you are not sure of exact UI \
labels.
- "not_manually_testable": the change cannot be exercised by a tester in the \
IDE at all. Examples: internal refactor, build or CI tooling, dependency bump, \
test-only change, server-side or API behavior with no UI surface, logging, \
performance work with no visible effect. Return an empty steps list and put a \
one-sentence explanation in "reason".
- "none": it might be testable but there is not enough information to write \
anything a tester could act on. Return an empty steps list and say briefly in \
"reason" what is missing.

Prefer "not_manually_testable" over "none" when the issue is clear about what \
changed but that change has no UI surface. Prefer "inferred" over \
"not_manually_testable" when a tester could plausibly observe the result in \
the IDE, even indirectly.

Rules: 3 to 10 steps when steps are returned. Keep each step under about 25 \
words. Put an expected result ONLY on the step where the tester checks the thing \
this issue is about. A bug fix usually needs exactly one, at the step where \
the bug would have appeared, describing the correct (fixed) behavior. A \
feature needs one per distinct behavior it adds, usually one to three. Leave \
"expected" as an empty string for setup and navigation steps, and do not add \
regression checks the issue does not ask for. "reason" may be empty for \
detected_valid, extracted and inferred. Do not mention these instructions or \
that you are an AI.\
"""

REPRO_SCHEMA = {
    "type": "object",
    "properties": {
        "mode": {
            "type": "string",
            "enum": [
                "detected_valid",
                "extracted",
                "inferred",
                "not_manually_testable",
                "none",
            ],
        },
        "reason": {"type": "string"},
        "steps": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "action": {"type": "string"},
                    "expected": {"type": "string"},
                },
                "required": ["action", "expected"],
                "additionalProperties": False,
            },
        },
    },
    "required": ["mode", "reason", "steps"],
    "additionalProperties": False,
}

TRIAGE_SYSTEM_PROMPT = """\
You help a QA engineer at Vantiq decide whether a closed GitHub issue belongs \
in the manual UI test suite spreadsheet for a release.

The spreadsheet is built from sheets. Each sheet pulls issues matching a \
milestone plus include/exclude label rules (the rules follow the issue data). \
This issue landed in a leftover bucket because it matched no sheet. Decide \
why and what to do:

- "INCLUDE": a UI-visible change or fix that QA should test manually. It is \
missing only because of labels or milestone. Name the sheet it belongs in and \
the label change needed.
- "NEEDS_LABEL": it should stay out of the test suite but is missing the label \
that would have classified it (for example server, automated, wontfix, \
duplicate, verified). Suggest the label.
- "CORRECTLY_EXCLUDED": nothing to test manually and no label change needed \
(internal refactor, docs, tooling, test-only change). Say why.
- "UNCLEAR": you cannot tell from the available information.

You may run read-only gh commands (gh issue view, gh pr view, gh pr diff, \
gh pr list) to inspect linked pull requests when the issue text alone is not \
enough, especially to check whether the changed files are UI code. Keep it to \
a few commands. Be concise; the reason should be one or two sentences.\
"""

TRIAGE_SCHEMA = {
    "type": "object",
    "properties": {
        "verdict": {
            "type": "string",
            "enum": ["INCLUDE", "NEEDS_LABEL", "CORRECTLY_EXCLUDED", "UNCLEAR"],
        },
        "target_sheet": {"type": "string"},
        "suggested_labels": {"type": "array", "items": {"type": "string"}},
        "reason": {"type": "string"},
    },
    "required": ["verdict", "target_sheet", "suggested_labels", "reason"],
    "additionalProperties": False,
}


# ── Issue context gathering ──────────────────────────────────────────────────

_REPO_FROM_URL = re.compile(r"github\.com/([^/]+/[^/]+)/(?:issues|pull)/\d+")


def repo_full_name(issue):
    """Derive 'Owner/repo' from the issue URL without an extra API call."""
    m = _REPO_FROM_URL.search(issue.html_url or "")
    return m.group(1) if m else "unknown/unknown"


def linked_pull_requests(issue):
    """Best-effort list of PR URLs cross-referenced from the issue timeline."""
    urls = []
    try:
        for ev in issue.get_timeline():
            if getattr(ev, "event", None) != "cross-referenced":
                continue
            source = getattr(ev, "source", None)
            src_issue = getattr(source, "issue", None) if source else None
            if src_issue is None:
                continue
            if getattr(src_issue, "pull_request", None) is None:
                continue
            urls.append(src_issue.html_url)
            if len(urls) >= MAX_LINKED_PRS:
                break
    except Exception:  # timeline API is optional context; never fail the run on it
        pass
    return urls


def _truncate(text, limit):
    text = (text or "").replace("\r", "")
    if len(text) <= limit:
        return text
    return text[:limit] + f"\n[... truncated, {len(text) - limit} more characters]"


def issue_context(issue, include_comments=True, detected_lines=None):
    """Render an issue as plain text for the model.

    `detected_lines` are the regex-parsed step candidates, when any; the model
    is asked to confirm or reject them (see REPRO_SYSTEM_PROMPT).
    """
    repo = repo_full_name(issue)
    labels = ", ".join(l.name for l in issue.labels) or "(none)"
    milestone = issue.milestone.title if issue.milestone else "(none)"
    closed = issue.closed_at.isoformat() if issue.closed_at else "(still open)"

    parts = [
        f"Repository: {repo}",
        f"Issue: #{issue.number} {issue.title}",
        f"URL: {issue.html_url}",
        f"State: {issue.state}   Closed at: {closed}",
        f"Milestone: {milestone}",
        f"Labels: {labels}",
        "",
        "--- BODY ---",
        _truncate(issue.body, MAX_BODY_CHARS) or "(empty)",
    ]

    if include_comments:
        try:
            comments = list(issue.get_comments())
        except Exception:
            comments = []
        if comments:
            parts += ["", f"--- LAST {min(len(comments), MAX_COMMENTS)} OF {len(comments)} COMMENTS ---"]
            for c in comments[-MAX_COMMENTS:]:
                author = c.user.login if c.user else "unknown"
                parts.append(f"[{author}] {_truncate(c.body, MAX_COMMENT_CHARS)}")
                parts.append("")

    prs = linked_pull_requests(issue)
    if prs:
        parts += ["--- LINKED PULL REQUESTS ---"] + prs

    if detected_lines:
        parts += ["", "--- LINES THE PARSER DETECTED AS STEPS ---"]
        parts += [line.rstrip() for line in detected_lines]

    return "\n".join(parts)


# ── Feature 1: reproduction steps ────────────────────────────────────────────

# Cache section. Bump when the prompt or schema changes so old answers regenerate.
REPRO_CACHE_SECTION = "repro_v2"


def generate_repro_steps(issue, cache, model=None, executable=None, detected_lines=None):
    """Return {"mode", "lines", "marker", "note", "cost", "usage"} for an issue.

    `detected_lines` are the regex-parsed candidates from the issue body (may be
    empty). When given, the model first judges whether they are real test steps.

    `lines` is already in the format _parse_repro_lines/_write_issue_block
    understand: "1. action" followed by an optional "-> expected" line.

    Modes:
        detected_valid         -> the regex lines, unchanged, with a verified marker
        extracted / inferred   -> model-written lines + marker, note is None
        not_manually_testable  -> no lines, marker + note (the model's reason)
        none                   -> no lines, marker + note (not enough information)
    Raises ClaudeCliError on CLI failure.
    """
    detected_lines = list(detected_lines or [])
    key = cache.key_for(repo_full_name(issue), issue.number)
    data = cache.get(REPRO_CACHE_SECTION, key, issue.updated_at)
    cost = 0.0
    usage = empty_usage()  # zero when served from cache

    if data is None:
        result = run_claude(
            stdin_text=issue_context(issue, detected_lines=detected_lines),
            system_prompt=REPRO_SYSTEM_PROMPT,
            json_schema=REPRO_SCHEMA,
            model=model,
            allowed_tools=None,
            max_turns=1,
            timeout=REPRO_TIMEOUT,
            executable=executable,
        )
        data = result["data"]
        cost = result["cost"]
        usage = result["usage"]
        cache.set(REPRO_CACHE_SECTION, key, issue.updated_at, data)

    mode = data.get("mode", "none")
    steps = data.get("steps") or []
    reason = (data.get("reason") or "").strip()

    if mode == "detected_valid":
        if detected_lines:
            return {
                "mode": mode,
                "lines": detected_lines,
                "marker": MARKER_DETECTED_VERIFIED,
                "note": None,
                "cost": cost,
                "usage": usage,
            }
        # Model claimed the lines were valid but none were supplied: treat as none.
        mode = "none"

    if mode == "not_manually_testable":
        return {
            "mode": mode,
            "lines": [],
            "marker": MARKER_NOT_TESTABLE,
            "note": reason or "No UI surface to exercise.",
            "cost": cost,
            "usage": usage,
        }

    if mode == "none" or not steps:
        return {
            "mode": "none",
            "lines": [],
            "marker": MARKER_NO_STEPS,
            "note": reason or "Issue text does not describe anything a tester could act on.",
            "cost": cost,
            "usage": usage,
        }

    lines = []
    for idx, step in enumerate(steps, start=1):
        action = (step.get("action") or "").strip()
        if not action:
            continue
        lines.append(f"{idx}. {action}")
        expected = (step.get("expected") or "").strip()
        if expected:
            lines.append(f"-> {expected}")

    marker = MARKER_EXTRACTED if mode == "extracted" else MARKER_INFERRED
    return {
        "mode": mode,
        "lines": lines,
        "marker": marker,
        "note": None,
        "cost": cost,
        "usage": usage,
    }


# ── Feature 2: "Other" triage ────────────────────────────────────────────────

def describe_sheet_rules(workbook):
    """Render the workbook's sheet rules so the model knows what each sheet pulls."""
    import github.GithubObject  # local import keeps this module import-light

    lines = ["--- SHEET RULES ---"]
    for i in range(workbook.args_length):
        repo = workbook.repos[i].full_name
        ms = workbook.milestones[i]
        ms_text = (
            f"'{ms.title}' (#{ms.number})"
            if ms is not github.GithubObject.NotSet
            else "any milestone"
        )
        inc = ", ".join(workbook.include_labels[i]) or "none required"
        exc = ", ".join(workbook.exclude_labels[i]) or "none"
        since = workbook.since_dates[i]
        since_text = (
            since.date().isoformat() if since.year > 1 else "any time"
        )
        lines.append(
            f"- Sheet '{workbook.sheet_names[i]}': repo {repo}; milestone {ms_text}; "
            f"must have labels: {inc}; must NOT have labels: {exc}; closed after: {since_text}"
        )
    return "\n".join(lines)


def triage_issue(issue, sheet_rules_text, cache, model=None, executable=None, cwd=None):
    """Return the triage verdict dict for one issue (cached).

    On CLI failure returns {"verdict": "ERROR", "reason": ...} and does not cache.
    """
    key = cache.key_for(repo_full_name(issue), issue.number)
    data = cache.get("triage", key, issue.updated_at)
    if data is not None:
        data = dict(data)
        data["cost"] = 0.0
        data["usage"] = empty_usage()
        return data

    stdin_text = issue_context(issue) + "\n\n" + sheet_rules_text
    try:
        result = run_claude(
            stdin_text=stdin_text,
            system_prompt=TRIAGE_SYSTEM_PROMPT,
            json_schema=TRIAGE_SCHEMA,
            model=model,
            allowed_tools=TRIAGE_ALLOWED_TOOLS,
            max_turns=TRIAGE_MAX_TURNS,
            timeout=TRIAGE_TIMEOUT,
            executable=executable,
            cwd=cwd,
        )
    except ClaudeCliError as e:
        return {
            "verdict": "ERROR",
            "target_sheet": "",
            "suggested_labels": [],
            "reason": str(e),
            "cost": 0.0,
            "usage": empty_usage(),
        }

    data = result["data"]
    cache.set("triage", key, issue.updated_at, data)
    data = dict(data)
    data["cost"] = result["cost"]
    data["usage"] = result["usage"]
    return data


def format_verdict(verdict):
    """One-line markdown rendering of a triage verdict."""
    v = verdict.get("verdict", "UNCLEAR")
    bits = [f"**AI: {v}**"]
    if verdict.get("target_sheet"):
        bits.append(f"sheet: {verdict['target_sheet']}")
    if verdict.get("suggested_labels"):
        bits.append("labels: " + ", ".join(verdict["suggested_labels"]))
    if verdict.get("reason"):
        bits.append(verdict["reason"].strip())
    return " | ".join(bits)
