import argparse, re
import github.GithubObject
import xlsxwriter

from config import TOKEN
from github import Github
from datetime import datetime, timedelta, timezone
from dateutil.parser import parse
from openpyxl import load_workbook


# If you use TFA you need to auth using an access token instead of username/password
g = Github(TOKEN)
# Init a WorkBook

class wbMain():
	g = Github(TOKEN)
	#Init class, set everything to NotSet
	def __init__(self, aLabel, eLabel, milestoneNum, date, repo, sheetNum, sheetName, workbookName, tabColor):
		self.iLabelList = aLabel
		self.eLabelList = eLabel
		self.repo = g.get_repo(f'Vantiq/{repo}')
		self.milestone = self.repo.get_milestone(milestoneNum) if milestoneNum else github.GithubObject.NotSet
		self.since = parse(' '.join(date)) if date else github.GithubObject.NotSet
		self.numRows = 30
		self.sheetName = f'{" ".join(self.iLabelList)} Issues' if not sheetName else sheetName
		self.tabColor = tabColor

	def getIssues(self):
		# First get all of the issues that fit the criteria
		issueList = list(self.repo.get_issues(state='all', labels=self.iLabelList, milestone=self.milestone, since=self.since, direction='asc'))
		for label in self.eLabelList:
			issueList = [i for i in issueList if label not in [l.name for l in i.labels]]
		return issueList

	def writeToSheet(self):
		wb = xlsxwriter.Workbook(f'{wbName}.xlsx')
		cell_format = wb.add_format({'bold': True, 'bg_color': '#d7dbd8'})
		cell_format.set_text_wrap()

		# Helper function to split the list into chunks
		def chunks(lst, n):
			for i in range(0, len(lst), n):
				yield lst[i:i + n]
		# Get all of the issues with the given states
		issueList = self.getIssues()
		# Split the issueList into chunks
		issueList = list(chunks(issueList, self.numRows))
		for idx, subList in enumerate(issueList):
			ws = wb.add_worksheet(self.sheetName+' #'+str(idx+1))
			if self.tabColor:
				ws.set_tab_color(self.tabColor)
			curRow = 0
			ws.set_column(1, 1, 70)
			ws.set_column(3, 3, 30)
			ws.set_column(5, 6, 40)
			ws.set_column(8, 8, 18)
			for i, issue in enumerate(subList):
				# Format the top row
				for j in range(1, 8):
					ws.write(curRow, j, '', cell_format)
				# Write the issue number and issue title, and link the text back to the original issue
				ws.write_url(curRow, 1, issue.html_url, cell_format, string='#{} {}'.format(issue.number, issue.title))
				ws.write(curRow, 3, 'Tester:', cell_format)
				ws.write(curRow, 8, 'Automation Status:', cell_format)
				curRow+=1
				# Write the bug number
				ws.write(curRow, 0, i+1)
				ws.write(curRow, 2, 'TC: Detail')
				ws.write(curRow, 4, 'Step #:')
				ws.write(curRow, 5, 'Test Steps:')
				ws.write(curRow, 6, 'Validation:')
				ws.write(curRow, 7, 'Status (Pass/Fail/Blocked)')
				ws.write(curRow, 8, 'Issue #')
				issueText = []
				if issue.body:
					# Pull all steps marked by numbering or bullet points, as well as validations (--->)
					issueText = [b.replace('\r', '') for b in issue.body.split('\n') if b \
					and(re.match(r'^\d+\.', b) or re.match(r'^\s*-+>', b) or re.match(r'^-+>', b) or re.match(r'^\*', b))]
					curRow+=1
				# If any steps were found, 
				if issueText:
					ws.write(curRow, 5, 'These steps were autogenerated!')
					curRow+=1
				else:
					curRow+=3
				stepNum=1
				for repro_step in issueText:
					# If it starts with a digit
					if re.match(r'^\d+\.', repro_step) or re.match(r'^\*', repro_step):
						# Remove any leading digits or bullet points
						repro_step = re.sub(r'^\d+\s*\.', r'', repro_step)
						repro_step = re.sub(r'^\*\s*', '', repro_step)
						# Remove any links
						repro_step = re.sub(r'\[(.*)\]\((.*)\)', '\1', repro_step)
						ws.write(curRow, 5, repro_step)
						ws.write(curRow, 4, stepNum)
						stepNum+=1
						curRow+=1
					if re.match(r'^\s+-+>', repro_step) or re.match(r'^-+>', repro_step):
						# Remove the arrow
						repro_step = re.sub(r'-+>\s*', '', repro_step)
						ws.write(curRow-1, 6, repro_step)


				curRow+=1
		wb.close()



parser = argparse.ArgumentParser(description='IssueWriter: From Issues to Sheets')

parser.add_argument('-al','--aLabel', help="""List of labels to include. If more than one label is specified, the program will
	find issues with ALL labels.""", nargs='+', default=github.GithubObject.NotSet)

parser.add_argument('-el','--eLabel', help="""List of labels to exclude. If more than one label is specified, the program will
	find issues with NONE of the labels""", nargs='+', default=[])

parser.add_argument('-m','--milestoneNum', help="""Number of milestone to filter with.\n
	1.32 Maintenance = 10\n
	1.33 Maintenance = 11\n
	Release 1.34 = 12""", type=int, default=0)

parser.add_argument('-d','--date', help="""Datetime object to act as deadline. Will get all issues created, edited, 
	or commented on AFTER the datetime object""", nargs='+', default=[])

parser.add_argument('-r','--repo', help='Repository from which issues are pulled', required=True)

parser.add_argument('-n', '--sheetNum', help='The number of issues per sheet', type=int, default=30)

parser.add_argument('-sn', '--sheetName', help='The name for the sheets in the Workbook')

parser.add_argument('-wn', '--workbookName', help='The name for workbook. (Full File)')

parser.add_argument('-tc', '--tabColor', help='Color for the created tabs. Can be a string or or HEX. (#FF9900)', default=None)

# parser.add_argument('-ew', '--existingWorkbook', help='Existing Worksheet to copy data from. Any new sheets created will be placed at the end of the worksheet', default=None)

args = vars(parser.parse_args())
wbName = args['workbookName']


newWb = wbMain(**args)
newWb.writeToSheet()

# TODO:
# Add color